kind: pipeline
type: docker
name: default

steps:
  # Step 1: 拉取代碼
  - name: checkout
    image: alpine/git
    commands:
      - git clone https://github.com/a607ernie/Ptt-Stock-Data.git
      - git checkout main

  # Step 2: 安裝依賴並執行腳本
  - name: run-script
    image: python:3.10
    # environment:
    #   SLACK_WEBHOOK:
    #     from_secret: slack_webhook
    #   LINE_Channel_ACCESS_TOKEN:
    #     from_secret: line_channel_access_token
    #   LINE_CHANNEL_ID:
    #     from_secret: line_channel_id
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - python main.py

  # Step 3: 提交更改至 GitHub
  - name: push-changes
    image: alpine/git
    environment:
      GIT_USERNAME:
        from_secret: git_username
      GIT_EMAIL:
        from_secret: git_email
      GIT_ACCESS_TOKEN:
        from_secret: git_access_token
    commands:
      - git config --global user.name ${GIT_USERNAME}
      - git config --global user.email ${GIT_EMAIL}
      - git add .
      - git commit -m "Update stock information from PTT" || echo "No changes to commit"
      - git push https://${GIT_USERNAME}:${GIT_ACCESS_TOKEN}@github.com/${GIT_USERNAME}/Ptt-Stock-Data.git main


trigger:
  schedule:
    - cron: "0 */12 * * *" # 每 12 小時執行一次
